import * as stylex from '@stylexjs/stylex';
import { colors } from './tokens.stylex';

export const s = stylex.create({
  page: { minHeight: '100vh', backgroundColor: colors.paper, color: colors.ink, fontSize: 15, lineHeight: 1.55 },
  layout: { display: 'grid', gridTemplateColumns: { default: '224px minmax(0, 1fr)', '@media (max-width: 800px)': 'minmax(0, 1fr)' }, minHeight: '100vh' },
  sidebar: { backgroundColor: colors.navy, color: colors.surface, padding: { default: '34px 20px', '@media (max-width: 800px)': '20px' }, display: 'flex', flexDirection: 'column', gap: 32 },
  brand: { display: 'flex', alignItems: 'center', gap: 12, fontSize: 24, fontWeight: 650, letterSpacing: '-1px', textDecoration: 'none' },
  mark: { display: 'grid', gridTemplateColumns: '12px 12px', gap: 3, transform: 'rotate(-25deg)' },
  dot: { width: 12, height: 12, borderRadius: '50%', backgroundColor: colors.coral },
  dotPink: { backgroundColor: colors.rose },
  dotPeach: { backgroundColor: colors.peach, gridColumn: '1 / 3', justifySelf: 'center' },
  nav: { display: 'flex', flexDirection: { default: 'column', '@media (max-width: 800px)': 'row' }, flexWrap: 'wrap', gap: 8 },
  navLink: { display: 'flex', alignItems: 'center', gap: 12, padding: '13px 16px', borderRadius: 14, textDecoration: 'none', color: colors.navyMuted, fontWeight: 550, minHeight: 48, backgroundColor: { default: 'transparent', ':hover': colors.navySurface }, flex: { default: 'initial', '@media (max-width: 800px)': '1 0 40%' } },
  activeNav: { color: colors.ink, backgroundColor: { default: colors.peach, ':hover': colors.peach } },
  sideBottom: { marginTop: 'auto', color: colors.navyMuted, fontSize: 12, display: { default: 'grid', '@media (max-width: 800px)': 'none' }, gap: 14 },
  main: { padding: { default: '30px 40px 50px', '@media (max-width: 1100px)': '28px', '@media (max-width: 600px)': '24px 16px' }, minWidth: 0, width: '100%', maxWidth: 1600, marginInline: 'auto' },
  topbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginBottom: 36, fontSize: 12, color: colors.muted },
  stack: { display: 'grid', gap: 24 },
  tight: { display: 'grid', gap: 12 },
  row: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
  between: { justifyContent: 'space-between' },
  grid: { display: 'grid', gridTemplateColumns: { default: 'repeat(2, minmax(0, 1fr))', '@media (max-width: 1000px)': 'minmax(0, 1fr)' }, gap: 20 },
  thirds: { display: 'grid', gridTemplateColumns: { default: 'repeat(3, minmax(0, 1fr))', '@media (max-width: 1100px)': 'minmax(0, 1fr)' }, gap: 20 },
  card: { padding: { default: 28, '@media (max-width: 600px)': 20 }, backgroundColor: colors.surface, borderRadius: 24, minWidth: 0 },
  inset: { backgroundColor: colors.paper, borderRadius: 16, padding: 18 },
  hero: { backgroundImage: colors.gradient, color: colors.navy, minHeight: 240, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', justifyContent: 'space-between', gap: 24 },
  eyebrow: { fontSize: 11, fontWeight: 700, letterSpacing: '1.5px', textTransform: 'uppercase' },
  h1: { fontSize: { default: 38, '@media (max-width: 600px)': 30 }, fontWeight: 600, letterSpacing: '-1.4px', lineHeight: 1.2, overflowWrap: 'anywhere', outline: 'none' },
  h2: { fontSize: 21, fontWeight: 600, letterSpacing: '-.5px', lineHeight: 1.3, overflowWrap: 'anywhere' },
  h3: { fontSize: 16, fontWeight: 650, overflowWrap: 'anywhere' },
  muted: { color: colors.muted },
  small: { fontSize: 12 },
  metric: { fontSize: 38, fontWeight: 550, letterSpacing: '-1.5px', lineHeight: 1.1 },
  button: { border: '1px solid transparent', backgroundColor: { default: colors.navy, ':hover': colors.navySurface, ':disabled': colors.muted }, color: colors.surface, padding: '11px 18px', borderRadius: 12, fontWeight: 600, minHeight: 44, textDecoration: 'none', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8, textAlign: 'center' },
  secondary: { backgroundColor: { default: colors.paper, ':hover': colors.line, ':disabled': colors.line }, color: colors.ink, borderColor: colors.line },
  light: { backgroundColor: { default: colors.surface, ':hover': colors.coralSoft }, color: colors.navy },
  badge: { display: 'inline-flex', alignItems: 'center', width: 'fit-content', padding: '5px 10px', borderRadius: 20, backgroundColor: colors.paper, fontSize: 11, fontWeight: 600, color: colors.muted },
  good: { color: colors.green, backgroundColor: colors.greenSoft },
  pink: { color: colors.roseInk, backgroundColor: colors.roseSoft },
  empty: { padding: '32px 12px', display: 'grid', gap: 12, justifyItems: 'start' },
  error: { backgroundColor: colors.coralSoft, padding: 18, borderRadius: 14, border: '1px solid #e98a71', overflowWrap: 'anywhere' },
  notice: { backgroundColor: colors.roseSoft, padding: 18, borderRadius: 14, color: colors.roseInk },
  list: { listStyle: 'none', margin: 0, padding: 0, display: 'grid' },
  listItem: { paddingBlock: 16, borderBottom: `1px solid ${colors.line}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' },
  link: { fontWeight: 600, textUnderlineOffset: 4, overflowWrap: 'anywhere' },
  field: { display: 'grid', gap: 7, fontWeight: 550, fontSize: 14, minWidth: 0 },
  input: { width: '100%', minWidth: 0, minHeight: 46, padding: '11px 13px', border: `1px solid ${colors.line}`, borderRadius: 12, color: colors.ink, backgroundColor: colors.surface, fontWeight: 400 },
  textarea: { minHeight: 100, resize: 'vertical' },
  range: { width: '100%', minWidth: 0, minHeight: 44, margin: 0 },
  definitionList: { margin: 0 },
  definitionValue: { margin: 0, fontWeight: 650 },
  full: { gridColumn: '1 / -1' },
  avatar: { width: 44, height: 44, flexShrink: 0, borderRadius: 14, display: 'grid', placeItems: 'center', backgroundColor: colors.peach, fontWeight: 650, fontSize: 18 },
  wrap: { overflowWrap: 'anywhere', whiteSpace: 'pre-wrap' },
  divider: { border: 0, borderTop: `1px solid ${colors.line}`, marginBlock: 8 },
  skip: { position: 'fixed', top: { default: -100, ':focus': 12 }, left: 12, zIndex: 20, backgroundColor: colors.surface, color: colors.ink, padding: 12 },
});
